// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ18U8lC-N4eveavf6YgidZVFAA9TzZus',
    appId: '1:100969452264:web:6bbbe550e8c1e0458d2f5d',
    messagingSenderId: '100969452264',
    projectId: 'fir-clib-ebuc',
    authDomain: 'fir-clib-ebuc.firebaseapp.com',
    storageBucket: 'fir-clib-ebuc.firebasestorage.app',
    measurementId: 'G-5RC3H8JFKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACPRPf6UrNhFbJe45HChdE6MNQWAVH0VU',
    appId: '1:100969452264:android:108312d5c93f73348d2f5d',
    messagingSenderId: '100969452264',
    projectId: 'fir-clib-ebuc',
    storageBucket: 'fir-clib-ebuc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ18U8lC-N4eveavf6YgidZVFAA9TzZus',
    appId: '1:100969452264:web:0f1aefa5956ea3918d2f5d',
    messagingSenderId: '100969452264',
    projectId: 'fir-clib-ebuc',
    authDomain: 'fir-clib-ebuc.firebaseapp.com',
    storageBucket: 'fir-clib-ebuc.firebasestorage.app',
    measurementId: 'G-WZ6PV8W9ZK',
  );
}
